ALTER TABLE `tombs` DROP INDEX `UNIQUE_TOMB`, ADD UNIQUE `UNIQUE_TOMB` (`SECTION_LETTER_ID`, `LOT_NUMBER`, `OWNER_ID`) USING BTREE;
ALTER TABLE `tombs` ADD `PLOT_NUMS` VARCHAR(80) NULL DEFAULT NULL ;
ALTER TABLE `tombs` ADD `NOTES` LONGTEXT NULL DEFAULT NULL ;
INSERT INTO `actions` (`ID`, `ACTION`) VALUES (NULL, 'fetchPlotNumbersList');