CREATE TABLE `accessible_modules` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `MODULE` varchar(60) NOT NULL UNIQUE,
    `DESCRIPTION` varchar(150) NOT NULL,
    `GUEST_ACCESS` tinyint(1) NOT NULL CHECK (`GUEST_ACCESS` = 1 or `GUEST_ACCESS` = 0),
    PRIMARY KEY (`ID`)
);
CREATE TABLE `actions`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `ACTION` varchar(100) NOT NULL UNIQUE,
    PRIMARY KEY (`ID`)
);
CREATE TABLE `actions_modules`(
    `ACTION_ID` INT (11) NOT NULL,
    `MODULE_ID` INT (11) NOT NULL 
);

ALTER TABLE `actions_modules`
ADD FOREIGN KEY (`ACTION_ID`) REFERENCES `actions` (`ID`) ON DELETE CASCADE,
ADD FOREIGN KEY (`MODULE_ID`) REFERENCES `accessible_modules` (`ID`) ON DELETE CASCADE;
